### PR TITLE
Creepy seeker Ghoul 👻 

### PR DESCRIPTION
**Pull request by tessapower**
Merging this PR will introduce a new `Spawnable` `Ghoul` character that seeks out the player in a creepy fashion! Still TODO is add the ghoul sprite and make sure it looks good when turning to face to player.

### CODE REVIEW

**Comment by TomasMorton** [comment]
Seeker.cs:
image

**Comment by TomasMorton** [comment]
image

**Comment by TomasMorton** [comment]
image
Is the physics interaction between the boat and the seeker intentional?

**Comment by tessapower** [comment]
@TomasMorton everything you found should now be fixed 😄

**Review by baconeta — APPROVED** [review]
Looks a lot better now. Code looks good. Functions very well :D

**Pull request merged**
